name: JSON check
on: 
  #push: {branches: master}
  pull_request: {branches: master} 
jobs:
  json-syntax-chk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: json-syntax-check
        uses: limitusus/json-syntax-check@v1
        with:
          pattern: "\\.json$"
